version: "3"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    links:
     - php
     - database
    volumes:
      - ../src:/var/www/html
      - ./server.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build: ./php-fpm-composer
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=drupal8
    volumes:
      - "../db:/var/lib/mysql"
    ports:
      - "3306:3306"
